PythonMN_Landing/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('conference.urls', namespace='conference')),
                       )

if settings.DEBUG:
    urlpatterns += patterns(
        url(r'', include('django.contrib.staticfiles.urls')),
    )

conference/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

urlpatterns = patterns('conference.views',
                       url(r'^$', 'home', name='home'),
                       url(r'about/$', 'about', name='about'),
                       url(r'signup/$', 'signup', name='signup'),
                       url(r'sponsors/$', 'sponsors', name='sponsors'),
                       url(r'volunteer/$', 'volunteer', name='volunteer')
                       )

conference/models.py
from django.db import models
from django.utils.encoding import smart_unicode


class SignUp(models.Model):
    email = models.EmailField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return smart_unicode(self.email)

conference/forms.py
from django import forms
from .models import SignUp


class SignUpForm(forms.ModelForm):
    class Meta:
        model = SignUp
        fields = ['email', ]
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control input-lg',
                                            'title': "Don't worry. We hate spam, and will not share your email with anyone.",
                                            'placeholder': "Enter your email address"})
        }

conference/views.py
import json
from django.shortcuts import HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import render
from .forms import SignUpForm


def home(request):

    form = SignUpForm()

    return render(request, "conference/base.html", {'form': form, })


def sponsors(request):

    form = SignUpForm()

    return render(request, "conference/sponsors.html", {'form': form, })


def about(request):

    form = SignUpForm()

    return render(request, "conference/about.html", {'form': form, })


def volunteer(request):

    form = SignUpForm()

    return render(request, "conference/volunteer.html", {'form': form, })


@require_POST
def signup(request):

    form = SignUpForm(request.POST)

    response_data = False

    if form.is_valid():
        form.save()
        response_data = True

    print response_data

    return HttpResponse(json.dumps(response_data), content_type="application/json")

conference/templates/conference/about.html
{% extends 'conference/base.html' %}

{% load sekizai_tags staticfiles pipeline %}

{% block big-heading %}
    <h1>About the PythonMN Conference</h1>
{% endblock big-heading %}

{% block content %}
    <h3>The PythonMN developers conference is all about the Python programming language.</h3>
    <h3>There will be presentations scheduled to go on throughout the day.</h3>
    <h3>Pythonistas of all ages and experience levels are welcome!</h3>
{% endblock content %}

{% block logo %}{% endblock logo %}

conference/templates/conference/base.html
{% load sekizai_tags staticfiles pipeline %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>PythonMN</title>
    <meta name="generator" content="Bootply"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static "conference/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
    <link href="{% static "conference/css/styles.css" %}" rel="stylesheet">
</head>

<body>

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PythonMN</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li {% if request.path == '/' %}
            class="active"
            {% else %} class=""
        {% endif %}><a href="/">Signup</a></li>
        <li {% if '/about' in request.path %}
            class="active"
            {% else %} class=""
        {% endif %}><a href="/about">About</a></li>
        <li {% if '/sponsors' in request.path %}
            class="active"
            {% else %} class=""
        {% endif %}><a href="/sponsors">Sponsors</a></li>
        <li {% if '/volunteer' in request.path %}
            class="active"
            {% else %} class=""
        {% endif %}><a href="/volunteer">Volunteer</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
{% endblock navbar %}

<br><br>

<div class="container-full">

    <div class="row">

        <div class="col-lg-12 text-center v-center">

            {% block big-heading %}
            <h1>PythonMN</h1>
            {% endblock big-heading %}


            {% block content %}
            <p class="lead">Sign-up for the PythonMN developers conference mailing list</p>
            {% endblock content %}

            {% block logo %}
            <img src="{% static "conference/img/pythonlogo.jpg" %}">
            {% endblock logo %}

            <br><br><br>

            {% block signup %}
            <form id="signup-form" class="col-lg-12" method="POST" action="{% url 'conference:signup' %}">
                <div class="input-group" style="width:340px;text-align:center;margin:0 auto;">
                    {% csrf_token %}
                    {{ form.email }}
                    <span class="input-group-btn">
                        <button class="btn btn-lg btn-primary" type="submit">OK</button>
                    </span>
                </div>
            </form>
            {% endblock signup %}
        </div>
    </div>
    <!-- /row -->

    <div class="row">

        <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
            <a href="#"><i class="icon-google-plus"></i></a>
            <a href="#"><i class="icon-facebook"></i></a>
            <a href="#"><i class="icon-twitter"></i></a>
            <a href="#"><i class="icon-github"></i></a>
        </div>

    </div>

    <br>

    <div class="row">
        <div class="col-lg-12 text-center v-center">
            <br><br>
            <p><a href="http://github.com/ajo3d">Page by AJO3D</a> &nbsp; ©Copyright 2015 AJO3D LLC.</p>
            <br>
        </div>
    </div>
</div>

<!-- script references -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script src="{% static "conference/js/bootstrap.min.js" %}"></script>

<script>
    $(document).ready(function (){
        $('#signup-form').submit(function (event){
            event.preventDefault();
            $.post('{% url 'conference:signup' %}', {
                email: $('#id_email').val(),
                csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
                processData: false,
                contentType: false
            }).success(function(data){

            });
        });
    });
</script>

</body>
</html>

conference/templates/conference/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Join Now</h1>
<form method="POST" action=""> {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" class="btn btn-success btn-block" >
</form>

{%  endblock %}

conference/templates/conference/sponsors.html
{% extends 'conference/base.html' %}

{% load sekizai_tags staticfiles pipeline %}

{% block big-heading %}
    <h1>Sponsor the PythonMN Conference</h1>
{% endblock big-heading %}

{% block content %}
    <h3>The PythonMN developers conference is looking for sponsors!</h3>
    <h3>Want to set up a booth? Get in touch with us</h3>
{% endblock content %}

{% block logo %}{% endblock logo %}

conference/templates/conference/volunteer.html
{% extends 'conference/base.html' %}

{% load sekizai_tags staticfiles pipeline %}

{% block big-heading %}
    <h1>Volunteer for the PythonMN Conference</h1>
{% endblock big-heading %}

{% block content %}
    <h3>The PythonMN developers conference is looking for volunteers!</h3>
    <h3>Want to help out? Get in touch with us</h3>
{% endblock content %}

{% block logo %}{% endblock logo %}